data:extend({
	{
		name = "todolist-show-button",
		setting_type = "runtime-per-user",
		type = "bool-setting",
		default_value = true,
		order = "tl-a",
		per_user = true,
	},
	{
		name = "todolist-show-log",
		setting_type = "runtime-per-user",
		type = "bool-setting",
		default_value = false,
		order = "tl-f",
		per_user = true,
	},
	{
		name = "todolist-window-height",
		setting_type = "runtime-per-user",
		type = "int-setting",
		default_value = 600,
		order = "tl-e",
		per_user = true,
	},
	{
		name = "todolist-enable-task-ownership",
		setting_type = "runtime-per-user",
		type = "bool-setting",
		default_value = true,
		order = "tl-b",
		per_user = true,
	},
	{
		name = "todolist-auto-assign",
		setting_type = "runtime-per-user",
		type = "bool-setting",
		default_value = false,
		order = "tl-ba",
		per_user = true,
	},
	{
		name = "todolist-click-edit-task",
		setting_type = "runtime-per-user",
		type = "string-setting",
		allowed_values = {"right-button", "middle-button"},
		default_value = "right-button",
		order = "tl-c",
		per_user = true,
	},
	{
		name = "todolist-translation-mode",
		setting_type = "runtime-per-user",
		type = "string-setting",
		allowed_values = {"default", "quest"},
		default_value = "default",
		order = "tl-d",
		per_user = true,
	}
})
